server:
  port: 8080

database:
  url: jdbc:postgresql://postgres:5432/car_shop
  username: car_shop_user
  password: some_password
  schema: data
  connectionPoolSize: 10

  liquibase:
    schema: infra
    changelog: db/changelog/changelog.yaml

springdoc:
  swagger-ui:
    path: /swagger-ui
  group-configs:
    - group: car-shop
      paths-to-match: /**
  packagesToScan:
    - com.lemondead1.carshopservice
  pathsToMatch:
    - /**