server:
  port: 8080

database:
  url: jdbc:postgresql://postgres:5432/car_shop
  username: car_shop_user
  password: some_password
  schema: data
  connectionPoolSize: 10

  liquibase:
    schema: infra
    changelog: db/changelog/changelog.yaml

logging:
  level:
    root: INFO
    com.lemondead1: DEBUG

spring:
  aop:
    proxyTargetClass: false

  jackson:
    serialization:
      writeDatesAsTimestamps: false
    propertyNamingStrategy: SNAKE_CASE

springdoc:
  openApi:
    info:
      version: 1.0.0
      title: CarShop Service API
      description: The API spec for the YLAB homework project.

    security:
      - basicAuth: [ ]

    components:
      securitySchemes:
        basicAuth:
          type: http
          scheme: basic

      # Do not remove this. Otherwise, it throws an NPE on access to the spec.
      schemas: { }

  swaggerUi:
    path: /swagger-ui

  groupConfigs:
    - group: car-shop
      pathsToMatch: /**

  packagesToScan:
    - com.lemondead1.carshopservice

  pathsToMatch:
    - /**