services:
  carshop-service:
    image: carshop-service
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "8080:8080"

  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=car_shop_user
      - POSTGRES_PASSWORD=some_password
      - POSTGRES_DB=car_shop
    restart: unless-stopped
    ports:
      - "5432:5432"
