services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=car_shop_user
      - POSTGRES_PASSWORD=some_password
      - POSTGRES_DB=car_shop
    restart: unless-stopped
    ports:
      - "5433:5432"